// Generated by scripts/generate-site-data.mjs. Do not edit by hand.
export const releaseData = {
  "pluginVersion": "0.3.0",
  "bridgeAbi": 1,
  "templateSchema": 1,
  "outputManifestSchema": 1,
  "platformContracts": {
    "wechat": {
      "runtimeType": "native",
      "apiNamespace": "wx",
      "subpackageField": "subpackages",
      "validation": {
        "exportSmoke": "automated",
        "devtoolCompile": "manual",
        "realDevice": "manual"
      }
    },
    "douyin": {
      "runtimeType": "native",
      "apiNamespace": "tt",
      "subpackageField": "subPackages",
      "validation": {
        "exportSmoke": "automated",
        "devtoolCompile": "manual",
        "realDevice": "manual"
      }
    },
    "tiktok": {
      "runtimeType": "native",
      "supportTier": "beta",
      "apiNamespace": "TTMinis.game",
      "nativeWebAssembly": "TTWebAssembly",
      "minimumClientVersion": "43.4.0",
      "subpackageField": "subpackages",
      "devtool": "ttmg",
      "devtoolVersion": "0.4.1-beta.wasm1",
      "packageLimitsBytes": {
        "total": 31457280,
        "main": 4194304,
        "independentSubpackage": 4194304
      },
      "validation": {
        "exportSmoke": "automated",
        "devtoolCompile": "required",
        "realDevice": "required-for-release"
      }
    },
    "alipay": {
      "runtimeType": "native",
      "supportTier": "experimental",
      "apiNamespace": "my",
      "subpackageField": "subpackages",
      "validation": {
        "exportSmoke": "automated",
        "devtoolCompile": "manual",
        "realDevice": "manual"
      }
    },
    "baidu": {
      "runtimeType": "native",
      "supportTier": "experimental",
      "apiNamespace": "swan",
      "subpackageField": "subpackages",
      "validation": {
        "exportSmoke": "automated",
        "devtoolCompile": "manual",
        "realDevice": "manual"
      }
    },
    "qq": {
      "runtimeType": "native",
      "supportTier": "experimental",
      "apiNamespace": "qq",
      "subpackageField": "subpackages",
      "requiresPrivateConfig": true,
      "validation": {
        "exportSmoke": "automated",
        "devtoolCompile": "manual",
        "realDevice": "manual"
      }
    },
    "kuaishou": {
      "runtimeType": "native",
      "supportTier": "experimental",
      "apiNamespace": "ks",
      "subpackageField": "subpackages",
      "forbidsJavascriptEval": true,
      "validation": {
        "exportSmoke": "automated",
        "devtoolCompile": "manual",
        "realDevice": "manual"
      }
    }
  },
  "bundled": {
    "godotVersion": "4.6.1.stable",
    "godotTag": "4.6.1-stable",
    "godotCommit": "14d19694e0c88a3f9e82d899a0400f27a24c176e",
    "emscriptenVersion": "4.0.3",
    "profile": "2d_full",
    "target": "release",
    "templateRevision": 1,
    "template": {
      "source": "bundled"
    },
    "platforms": {
      "wechat": "automated",
      "douyin": "automated",
      "tiktok": "automated",
      "alipay": "automated",
      "baidu": "automated",
      "qq": "automated",
      "kuaishou": "automated"
    }
  },
  "certified": [
    {
      "godotVersion": "4.6.1.stable",
      "godotTag": "4.6.1-stable",
      "godotCommit": "14d19694e0c88a3f9e82d899a0400f27a24c176e",
      "emscriptenVersion": "4.0.3",
      "profile": "2d_full",
      "target": "release",
      "templateRevision": 1,
      "template": {
        "source": "bundled"
      },
      "platforms": {
        "wechat": "automated",
        "douyin": "automated",
        "tiktok": "automated",
        "alipay": "automated",
        "baidu": "automated",
        "qq": "automated",
        "kuaishou": "automated"
      }
    }
  ]
} as const;
